### ISSUE TITLE
一直重启

### ISSUE THREAD

**Issue by yingerson** [onlyLTY/dockerCopilotZspace#3]
极空间Z4拉取镜像以后，一直重启中。请问如何解决？
2024-08-24T02:28:39.341093010Z 
2024-08-24T02:28:39.341123188Z goroutine 1 [running]:
2024-08-24T02:28:39.341135612Z main.main()
2024-08-24T02:28:39.341145013Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:28:41.252643232Z 2024-08-24T10:28:41.251+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:28:41.341547947Z 2024-08-24T10:28:41.341+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:28:41.341596255Z 2024-08-24T10:28:41.341+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:28:41.343879421Z panic: 请求错误，状态码:422
2024-08-24T02:28:41.343907584Z 
2024-08-24T02:28:41.343915517Z goroutine 1 [running]:
2024-08-24T02:28:41.343922646Z main.main()
2024-08-24T02:28:41.343932925Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:28:44.892186477Z 2024-08-24T10:28:44.891+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:28:44.991752369Z 2024-08-24T10:28:44.991+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:28:44.991801776Z 2024-08-24T10:28:44.991+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:28:44.994326419Z panic: 请求错误，状态码:422
2024-08-24T02:28:44.994397786Z 
2024-08-24T02:28:44.994406673Z goroutine 1 [running]:
2024-08-24T02:28:44.994414697Z main.main()
2024-08-24T02:28:44.994459287Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:28:51.720106180Z 2024-08-24T10:28:51.719+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:28:51.810175217Z 2024-08-24T10:28:51.809+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:28:51.810224555Z 2024-08-24T10:28:51.809+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:28:51.812263232Z panic: 请求错误，状态码:422
2024-08-24T02:28:51.812277796Z 
2024-08-24T02:28:51.812286232Z goroutine 1 [running]:
2024-08-24T02:28:51.812297065Z main.main()
2024-08-24T02:28:51.812307911Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:29:04.964870661Z 2024-08-24T10:29:04.964+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:29:05.054364615Z 2024-08-24T10:29:05.054+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:29:05.054415959Z 2024-08-24T10:29:05.054+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:29:05.056601620Z panic: 请求错误，状态码:422
2024-08-24T02:29:05.056618705Z 
2024-08-24T02:29:05.056635707Z goroutine 1 [running]:
2024-08-24T02:29:05.056643915Z main.main()
2024-08-24T02:29:05.056651013Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:29:31.010059836Z 2024-08-24T10:29:31.009+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:29:31.101117437Z 2024-08-24T10:29:31.100+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:29:31.101169149Z 2024-08-24T10:29:31.100+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:29:31.103234399Z panic: 请求错误，状态码:422
2024-08-24T02:29:31.103257239Z 
2024-08-24T02:29:31.103266128Z goroutine 1 [running]:
2024-08-24T02:29:31.103274273Z main.main()
2024-08-24T02:29:31.105122499Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:30:22.655473733Z 2024-08-24T10:30:22.654+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:30:22.756146930Z 2024-08-24T10:30:22.755+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:30:22.756228577Z 2024-08-24T10:30:22.755+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:30:22.758392476Z panic: 请求错误，状态码:422
2024-08-24T02:30:22.758422345Z 
2024-08-24T02:30:22.758430228Z goroutine 1 [running]:
2024-08-24T02:30:22.758437591Z main.main()
2024-08-24T02:30:22.758444805Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:31:23.118698488Z 2024-08-24T10:31:23.118+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:31:23.218176822Z 2024-08-24T10:31:23.217+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:31:23.218229336Z 2024-08-24T10:31:23.217+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:31:23.220292845Z panic: 请求错误，状态码:422
2024-08-24T02:31:23.220314966Z 
2024-08-24T02:31:23.220323868Z goroutine 1 [running]:
2024-08-24T02:31:23.220333705Z main.main()
2024-08-24T02:31:23.220343794Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:32:23.509845701Z 2024-08-24T10:32:23.509+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:32:23.610369270Z 2024-08-24T10:32:23.610+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:32:23.610423873Z 2024-08-24T10:32:23.610+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:32:23.612495045Z panic: 请求错误，状态码:422
2024-08-24T02:32:23.612509896Z 
2024-08-24T02:32:23.612517326Z goroutine 1 [running]:
2024-08-24T02:32:23.612527228Z main.main()
2024-08-24T02:32:23.612561309Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:33:23.972939196Z 2024-08-24T10:33:23.972+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:33:24.075238644Z 2024-08-24T10:33:24.074+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:33:24.075290394Z 2024-08-24T10:33:24.074+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:33:24.078874073Z panic: 请求错误，状态码:422
2024-08-24T02:33:24.078938400Z 
2024-08-24T02:33:24.078948605Z goroutine 1 [running]:
2024-08-24T02:33:24.078958918Z main.main()
2024-08-24T02:33:24.078969387Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:34:24.365940594Z 2024-08-24T10:34:24.365+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:34:24.454602945Z 2024-08-24T10:34:24.454+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:34:24.454656843Z 2024-08-24T10:34:24.454+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:34:24.457646873Z panic: 请求错误，状态码:422
2024-08-24T02:34:24.457666913Z 
2024-08-24T02:34:24.457675308Z goroutine 1 [running]:
2024-08-24T02:34:24.457685677Z main.main()
2024-08-24T02:34:24.457695942Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:35:24.765153178Z 2024-08-24T10:35:24.764+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:35:24.864798591Z 2024-08-24T10:35:24.864+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:35:24.864849412Z 2024-08-24T10:35:24.864+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:35:24.866901396Z panic: 请求错误，状态码:422
2024-08-24T02:35:24.866918182Z 
2024-08-24T02:35:24.866928424Z goroutine 1 [running]:
2024-08-24T02:35:24.866938714Z main.main()
2024-08-24T02:35:24.866946143Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751
2024-08-24T02:36:25.204427310Z 2024-08-24T10:36:25.204+08:00	[34;1m info [0;22m	未找到jwt或jwt已失效，重新获取jwt	caller=utiles/base.go:53
2024-08-24T02:36:25.293165386Z 2024-08-24T10:36:25.292+08:00	[31;1m error [0;22m	GetNewJwt error: 请求错误，状态码:422	caller=utiles/getImageList.go:17
2024-08-24T02:36:25.293217947Z 2024-08-24T10:36:25.292+08:00	[31;1m error [0;22m	panic获取镜像列表出错: 请求错误，状态码:422	caller=zspace/dockercopilot.go:60
2024-08-24T02:36:25.295356079Z panic: 请求错误，状态码:422
2024-08-24T02:36:25.295372358Z 
2024-08-24T02:36:25.295380279Z goroutine 1 [running]:
2024-08-24T02:36:25.295387522Z main.main()
2024-08-24T02:36:25.295397698Z 	github.com/onlyLTY/dockerCopilotZspace/zspace/dockercopilot.go:61 +0x751

**Comment by onlyLTY** [comment]
请检查host模式，account写极空间的创建账号

**Comment by yingerson** [comment]
> 请检查host模式，account写极空间的创建账号

感谢解答，问题解决
